networks:
  - name: "aws_subnet"
    cidr: 10.0.7.0/24
    policies:
      - ip: 10.0.7.224
        ports: [22]
      - hostname: "*.x.pipedream.net"
        ports: [443]
      - hostname: form3.tech
        ports: [443]
      - hostname: example.com
        ports: [443]
      - hostname: github.com
        ports: [443]
